package com.cashflowtracker.miranda.utils

enum class Countries(val label: String, val currency: Currencies) {
    // Eurozone Countries
    AUSTRIA("Austria", Currencies.EUR),
    BELGIUM("Belgium", Currencies.EUR),
    CROATIA("Croatia", Currencies.EUR),
    CYPRUS("Cyprus", Currencies.EUR),
    ESTONIA("Estonia", Currencies.EUR),
    FINLAND("Finland", Currencies.EUR),
    FRANCE("France", Currencies.EUR),
    GERMANY("Germany", Currencies.EUR),
    GREECE("Greece", Currencies.EUR),
    IRELAND("Ireland", Currencies.EUR),
    ITALY("Italy", Currencies.EUR),
    LATVIA("Latvia", Currencies.EUR),
    LITHUANIA("Lithuania", Currencies.EUR),
    LUXEMBOURG("Luxembourg", Currencies.EUR),
    MALTA("Malta", Currencies.EUR),
    NETHERLANDS("Netherlands", Currencies.EUR),
    PORTUGAL("Portugal", Currencies.EUR),
    SLOVAKIA("Slovakia", Currencies.EUR),
    SLOVENIA("Slovenia", Currencies.EUR),
    SPAIN("Spain", Currencies.EUR),

    // USD-based Countries
    UNITED_STATES("United States", Currencies.USD),
    PUERTO_RICO("Puerto Rico", Currencies.USD),
    GUAM("Guam", Currencies.USD),
    MARSHALL_ISLANDS("Marshall Islands", Currencies.USD),
    EL_SALVADOR("El Salvador", Currencies.USD),
    ECUADOR("Ecuador", Currencies.USD),
    EAST_TIMOR("East Timor", Currencies.USD),
    ZIMBABWE("Zimbabwe", Currencies.USD),

    // AUD-based Countries
    AUSTRALIA("Australia", Currencies.AUD),
    NAURU("Nauru", Currencies.AUD),
    KIRIBATI("Kiribati", Currencies.AUD),
    TUVALU("Tuvalu", Currencies.AUD),

    // CHF-based Country
    SWITZERLAND("Switzerland", Currencies.CHF),
    LIECHTENSTEIN("Liechtenstein", Currencies.CHF),

    // DKK-based Country
    DENMARK("Denmark", Currencies.DKK),
    GREENLAND("Greenland", Currencies.DKK),

    ARGENTINA("Argentina", Currencies.ARS),
    BANGLADESH("Bangladesh", Currencies.BDT),
    BRAZIL("Brazil", Currencies.BRL),
    CANADA("Canada", Currencies.CAD),
    CHINA("China", Currencies.CNY),
    CZECH_REPUBLIC("Czech Republic", Currencies.CZK),
    EGYPT("Egypt", Currencies.EGP),
    HONG_KONG("Hong Kong", Currencies.HKD),
    HUNGARY("Hungary", Currencies.HUF),
    ICELAND("Iceland", Currencies.ISK),
    INDIA("India", Currencies.INR),
    INDONESIA("Indonesia", Currencies.IDR),
    ISRAEL("Israel", Currencies.ILS),
    JAPAN("Japan", Currencies.JPY),
    KENYA("Kenya", Currencies.KES),
    MALAYSIA("Malaysia", Currencies.MYR),
    MEXICO("Mexico", Currencies.MXN),
    NEW_ZEALAND("New Zealand", Currencies.NZD),
    NIGERIA("Nigeria", Currencies.NGN),
    NORWAY("Norway", Currencies.NOK),
    PAKISTAN("Pakistan", Currencies.PKR),
    PHILIPPINES("Philippines", Currencies.PHP),
    POLAND("Poland", Currencies.PLN),
    RUSSIA("Russia", Currencies.RUB),
    SAUDI_ARABIA("Saudi Arabia", Currencies.SAR),
    SINGAPORE("Singapore", Currencies.SGD),
    SOUTH_AFRICA("South Africa", Currencies.ZAR),
    SOUTH_KOREA("South Korea", Currencies.KRW),
    SRI_LANKA("Sri Lanka", Currencies.LKR),
    SWEDEN("Sweden", Currencies.SEK),
    UNITED_ARAB_EMIRATES("United Arab Emirates", Currencies.AED),
    UNITED_KINGDOM("United Kingdom", Currencies.GBP),
    THAILAND("Thailand", Currencies.THB),
    TURKEY("Turkey", Currencies.TRY),
    VIETNAM("Vietnam", Currencies.VND)
}