package com.cashflowtracker.miranda.utils

enum class CurrencyEnum(val label: String, val symbol: String) {
    EUR("Euro", "€"),
    USD("US Dollar", "$"),
    GBP("British Pound", "£"),
    JPY("Japanese Yen", "¥"),
    AUD("Australian Dollar", "$"),
    CAD("Canadian Dollar", "$"),
    CHF("Swiss Franc", "Fr"),
    CNY("Chinese Yuan", "¥"),
    HKD("Hong Kong Dollar", "$"),
    NZD("New Zealand Dollar", "$"),
    RUB("Russian Ruble", "₽"),
    SGD("Singapore Dollar", "$"),
    SEK("Swedish Krona", "kr"),
    ZAR("South African Rand", "R"),
    KRW("South Korean Won", "₩"),
    ISK("Icelandic Krona", "kr"),
    INR("Indian Rupee", "₹"),
    MXN("Mexican Peso", "$"),
    BRL("Brazilian Real", "R$"),
    ARS("Argentine Peso", "$"),
    PLN("Polish Zloty", "zł"),
    NOK("Norwegian Krone", "kr"),
    DKK("Danish Krone", "kr"),
    HUF("Hungarian Forint", "Ft"),
    CZK("Czech Koruna", "Kč"),
    TRY("Turkish Lira", "₺"),
    AED("United Arab Emirates Dirham", "د.إ"),
    SAR("Saudi Riyal", "﷼"),
    MYR("Malaysian Ringgit", "RM"),
    THB("Thai Baht", "฿"),
    PHP("Philippine Peso", "₱"),
    IDR("Indonesian Rupiah", "Rp"),
    VND("Vietnamese Dong", "₫"),
    BDT("Bangladeshi Taka", "৳"),
    PKR("Pakistani Rupee", "₨"),
    LKR("Sri Lankan Rupee", "Rs"),
    ILS("Israeli Shekel", "₪"),
    EGP("Egyptian Pound", "£"),
    NGN("Nigerian Naira", "₦"),
    KES("Kenyan Shilling", "KSh")
}

enum class CountriesEnum(val label: String, val currency: CurrencyEnum) {
    // Eurozone Countries
    AUSTRIA("Austria", CurrencyEnum.EUR),
    BELGIUM("Belgium", CurrencyEnum.EUR),
    CROATIA("Croatia", CurrencyEnum.EUR),
    CYPRUS("Cyprus", CurrencyEnum.EUR),
    ESTONIA("Estonia", CurrencyEnum.EUR),
    FINLAND("Finland", CurrencyEnum.EUR),
    FRANCE("France", CurrencyEnum.EUR),
    GERMANY("Germany", CurrencyEnum.EUR),
    GREECE("Greece", CurrencyEnum.EUR),
    IRELAND("Ireland", CurrencyEnum.EUR),
    ITALY("Italy", CurrencyEnum.EUR),
    LATVIA("Latvia", CurrencyEnum.EUR),
    LITHUANIA("Lithuania", CurrencyEnum.EUR),
    LUXEMBOURG("Luxembourg", CurrencyEnum.EUR),
    MALTA("Malta", CurrencyEnum.EUR),
    NETHERLANDS("Netherlands", CurrencyEnum.EUR),
    PORTUGAL("Portugal", CurrencyEnum.EUR),
    SLOVAKIA("Slovakia", CurrencyEnum.EUR),
    SLOVENIA("Slovenia", CurrencyEnum.EUR),
    SPAIN("Spain", CurrencyEnum.EUR),

    // USD-based Countries
    UNITED_STATES("United States", CurrencyEnum.USD),
    PUERTO_RICO("Puerto Rico", CurrencyEnum.USD),
    GUAM("Guam", CurrencyEnum.USD),
    MARSHALL_ISLANDS("Marshall Islands", CurrencyEnum.USD),
    EL_SALVADOR("El Salvador", CurrencyEnum.USD),
    ECUADOR("Ecuador", CurrencyEnum.USD),
    EAST_TIMOR("East Timor", CurrencyEnum.USD),
    ZIMBABWE("Zimbabwe", CurrencyEnum.USD),

    // AUD-based Countries
    AUSTRALIA("Australia", CurrencyEnum.AUD),
    NAURU("Nauru", CurrencyEnum.AUD),
    KIRIBATI("Kiribati", CurrencyEnum.AUD),
    TUVALU("Tuvalu", CurrencyEnum.AUD),

    // CHF-based Country
    SWITZERLAND("Switzerland", CurrencyEnum.CHF),
    LIECHTENSTEIN("Liechtenstein", CurrencyEnum.CHF),

    // DKK-based Country
    DENMARK("Denmark", CurrencyEnum.DKK),
    GREENLAND("Greenland", CurrencyEnum.DKK),

    ARGENTINA("Argentina", CurrencyEnum.ARS),
    BANGLADESH("Bangladesh", CurrencyEnum.BDT),
    BRAZIL("Brazil", CurrencyEnum.BRL),
    CANADA("Canada", CurrencyEnum.CAD),
    CHINA("China", CurrencyEnum.CNY),
    CZECH_REPUBLIC("Czech Republic", CurrencyEnum.CZK),
    EGYPT("Egypt", CurrencyEnum.EGP),
    HONG_KONG("Hong Kong", CurrencyEnum.HKD),
    HUNGARY("Hungary", CurrencyEnum.HUF),
    ICELAND("Iceland", CurrencyEnum.ISK),
    INDIA("India", CurrencyEnum.INR),
    INDONESIA("Indonesia", CurrencyEnum.IDR),
    ISRAEL("Israel", CurrencyEnum.ILS),
    JAPAN("Japan", CurrencyEnum.JPY),
    KENYA("Kenya", CurrencyEnum.KES),
    MALAYSIA("Malaysia", CurrencyEnum.MYR),
    MEXICO("Mexico", CurrencyEnum.MXN),
    NEW_ZEALAND("New Zealand", CurrencyEnum.NZD),
    NIGERIA("Nigeria", CurrencyEnum.NGN),
    NORWAY("Norway", CurrencyEnum.NOK),
    PAKISTAN("Pakistan", CurrencyEnum.PKR),
    PHILIPPINES("Philippines", CurrencyEnum.PHP),
    POLAND("Poland", CurrencyEnum.PLN),
    RUSSIA("Russia", CurrencyEnum.RUB),
    SAUDI_ARABIA("Saudi Arabia", CurrencyEnum.SAR),
    SINGAPORE("Singapore", CurrencyEnum.SGD),
    SOUTH_AFRICA("South Africa", CurrencyEnum.ZAR),
    SOUTH_KOREA("South Korea", CurrencyEnum.KRW),
    SRI_LANKA("Sri Lanka", CurrencyEnum.LKR),
    SWEDEN("Sweden", CurrencyEnum.SEK),
    UNITED_ARAB_EMIRATES("United Arab Emirates", CurrencyEnum.AED),
    UNITED_KINGDOM("United Kingdom", CurrencyEnum.GBP),
    THAILAND("Thailand", CurrencyEnum.THB),
    TURKEY("Turkey", CurrencyEnum.TRY),
    VIETNAM("Vietnam", CurrencyEnum.VND)
}